Sidenav collapse
GSA/sam-styles pull request #372
Opened 2020-11-25 18:02 UTC by Bibek-Regmi

2020-12-04 15:46 UTC, davereed requested changes
Run a lint/format on the HTML files, a lot of extra spaces and oddities that can be cleaned up.

2020-12-04 15:46 UTC, davereed commented on src/components/06-miscellaneous/09-search layout/search layout.njk
> +                <p  Please try another search or go back to previous results.</p>
Missing a closing > on the P tag

2020-12-04 15:46 UTC, davereed commented on src/stylesheets/components/_card.scss
> +$theme-font-sans: 'source-sans-pro';
remove, not using this

2020-12-04 15:46 UTC, davereed commented on src/stylesheets/components/_sidenav.scss
> +$theme-font-sans: 'source-sans-pro';
remove, not using this

2020-12-07 13:53 UTC, Bibek-Regmi commented on src/components/06-miscellaneous/09-search layout/search layout.njk
> +                <p  Please try another search or go back to previous results.</p>
Closed p tag

2020-12-07 13:53 UTC, Bibek-Regmi commented on src/stylesheets/components/_card.scss
> +$theme-font-sans: 'source-sans-pro';
Updated

2020-12-07 13:53 UTC, Bibek-Regmi commented on src/stylesheets/components/_sidenav.scss
> +$theme-font-sans: 'source-sans-pro';
Updated

2020-12-07 21:29 UTC, yerramshilpa approved these changes

2020-12-07 21:30 UTC, merged